### PR TITLE
Moved admin configs from local proview

### PR DESCRIPTION
**Pull request by rohansharmasitoula**
## Description
- Please include a summary of the change.

## Github Issue
- Add github issue link and title (eg: resolves #123)

## Checklist before requesting a review
- [ ] One line description of the changes is added in the PR
- [ ] Issue is linked to the PR via commits (eg: resolves #123)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires only a documentation update

## Dependencies (if any):
- Mention any dependencies/issues for reviewers reference (eg: #1124 needs to be deployed before/after this PR)

## References (if any):
- [ ] Any reference documents to review before/after this PR review
- Add the links of any related PR/documents/diagrams for reviewers reference (eg: #link to understand login flow).

## Summary by CodeRabbit

- **New Features**
	- Expanded Proview integration with new configuration options for enhanced proctoring in quizzes.
- **Documentation**
	- Updated version and release numbers to reflect the latest build.

### CODE REVIEW

**Comment by manquer** [comment]
@rohansharmasitoula 

1. do not tag me for review unless you *really* *really* want my review. I have little time for reviewers and more than 40 developers to work with. 
2. If you do really really need my review just don't tag me, elaborate in comments why you do need my review over everyone else 
3. Do not tag so many reviewers, they have day jobs outside of reviewing code. Tag one person only, if they are not able to do so on time then tag the next person while removing the first person. 
4. If tag 5 people to review code, remember you will have to also review 5 times the code you write. How many reviews are you doing now ?

**Comment by manquer** [comment]
@rakeshprabhu @harish-talview Set some ground rules on reviews. @KeerthiHarish @merlano17 discourage this practice.

**Comment by rohansharmasitoula** [comment]
> @rohansharmasitoula
> 
> 1. do not tag me for review unless you _really_ _really_ want my review. I have little time for reviewers and more than 40 developers to work with.
> 2. If you do really really need my review just don't tag me, elaborate in comments why you do need my review over everyone else
> 3. Do not tag so many reviewers, they have day jobs outside of reviewing code. Tag one person only, if they are not able to do so on time then tag the next person while removing the first person.
> 4. If tag 5 people to review code, remember you will have to also review 5 times the code you write. How many reviews are you doing now ?

Sorry @manquer will not repeat this again. 
The reviews requests were automatically tagged to the code owners. Will check for a workaround to prevent it.

**Comment by devang1281** [comment]
@rohansharmasitoula closing this PR, please re-open or create a new PR when this feature is priortised.

**Pull request closed without merging**
